name: Release to Nuget

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Create Nuget Package
      run: dotnet pack -c Release /p:Version=${{ github.evemt.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/alonf/IoTHubClientGenerator/releases/tag/${{ github.evemt.release.tag_name}}"
      working-directory: ./Alonf.IoTHubClientGenerator
    - name: Archive Nuget Package
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: "**/*.nupkg"
     
     

   
